// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // Define your tables here
      // Example:
      // profiles: {
      //   Row: {
      //     id: string;
      //     email: string;
      //     full_name: string | null;
      //     avatar_url: string | null;
      //     created_at: string;
      //     updated_at: string;
      //   };
      //   Insert: {
      //     id: string;
      //     email: string;
      //     full_name?: string | null;
      //     avatar_url?: string | null;
      //     created_at?: string;
      //     updated_at?: string;
      //   };
      //   Update: {
      //     id?: string;
      //     email?: string;
      //     full_name?: string | null;
      //     avatar_url?: string | null;
      //     created_at?: string;
      //     updated_at?: string;
      //   };
      // };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
